Test App
mohametalmeari/math-magicians pull request #6
Opened 2023-06-06 08:19 UTC by mohametalmeari

- [ ] Test Operate Functionality
- [ ] Test Calculate Functionality
- [ ] Test Components
- [ ] Ren all tests

2023-06-06 08:43 UTC, Ibizugbe reviewed
Hi @mohametalmeari 👋👋👋, 

![INVALID](https://github.com/mohametalmeari/math-magicians/assets/64643995/83819086-d73d-4c90-b5cc-1530bc6b8c0d)


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have contributions from your learning partner🥲. Kindly note that this is a pair programing activity and you are required to work with your partner to complete this milestone. Please reach out to your partner and work with the person.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-07 09:08 UTC, julie-ify requested changes
## Hi @mohametalmeari and @tjay1760,

Good job so far!

## Highlights!
- Good code organization and tests ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 09:08 UTC, julie-ify commented on src/components/Layout.text.js
> +});
- [ ] You made an error in this file's name. Kindly rename this file to `.test.`, instead of `.text.`

2023-06-07 11:51 UTC, amejid approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct workflow :heavy_check_mark: 
- Jest snapshots used :heavy_check_mark: 
- User interactions tested with RTL :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 12:27 UTC, merged

2023-06-10 08:12 UTC, mohametalmeari commented
Thank you so much, happy weekend 🥂